// Problem28.cpp : Defines the entry point for the console application.
//

#include "stdafx.h"


int main()
{
  long long result = 1;
  // The top-right diagonal (1,9,25...) is formed by numbers generated by (2n+1)^2
  for (long long i = 1; i <= 500; ++i)
  {
    long long j = (2 * i + 1);
    result += j*j;
  }
  // The bottom-left diagonal (1,5,17...) is formed by numbers generated by (2n)^2 + 1
  // and the top-left and bottom right, when added, equate to the double of bottom-left,
  // so multiplying bottom-left by 3 will give us all three altogether.
  for (long long i = 1; i <= 500; ++i)
  {
    long long j = (4 * i * i) + 1;
    result += 3 * j;
  }
  printf("The diagonal sum is %lld\r\n", result);
  return 0;
}

